// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg_wES1q4b7YTdLV3I_R2gR6a3xV78sEM',
    appId: '1:868880906610:web:f85fdc0202e6e0d6f385eb',
    messagingSenderId: '868880906610',
    projectId: 'air-pollution-database',
    authDomain: 'air-pollution-database.firebaseapp.com',
    databaseURL: 'https://air-pollution-database-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'air-pollution-database.appspot.com',
    measurementId: 'G-GPJFMJBQ7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdyAvH1URvMfLEJklKrXL8wfDdTv2UzCs',
    appId: '1:868880906610:android:af14c53611222e85f385eb',
    messagingSenderId: '868880906610',
    projectId: 'air-pollution-database',
    databaseURL: 'https://air-pollution-database-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'air-pollution-database.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkWo_oiZ1htO9zYJvIEg9XXOyImnBCR_8',
    appId: '1:868880906610:ios:b6042d0b3362305df385eb',
    messagingSenderId: '868880906610',
    projectId: 'air-pollution-database',
    databaseURL: 'https://air-pollution-database-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'air-pollution-database.appspot.com',
    iosBundleId: 'com.example.airMonitoringApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkWo_oiZ1htO9zYJvIEg9XXOyImnBCR_8',
    appId: '1:868880906610:ios:b6042d0b3362305df385eb',
    messagingSenderId: '868880906610',
    projectId: 'air-pollution-database',
    databaseURL: 'https://air-pollution-database-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'air-pollution-database.appspot.com',
    iosBundleId: 'com.example.airMonitoringApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg_wES1q4b7YTdLV3I_R2gR6a3xV78sEM',
    appId: '1:868880906610:web:7ecc8c152b090f81f385eb',
    messagingSenderId: '868880906610',
    projectId: 'air-pollution-database',
    authDomain: 'air-pollution-database.firebaseapp.com',
    databaseURL: 'https://air-pollution-database-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'air-pollution-database.appspot.com',
    measurementId: 'G-8S7TX35X5L',
  );
}
